apiVersion: podmarker.kube-stack.me/v1
kind: PodMarker
metadata:
  name: podmarker-sample
spec:
  # TODO(user): Add fields here
  selector:
    matchLabels:
      app: vm
  addLabels:
    podIP: "{.status.podIP}"
  markLabels:
  - replicas: 2
    labels:
      testkey: value